# Generated by Django 3.2.5 on 2022-08-23 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='is_cropped',
            field=models.BooleanField(default=False),
        ),
    ]
